command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: DATABRICKS_CLIENT_ID
    value: 6c0908bb-6032-4410-a5e8-80688dc516e9
  - name: DATABRICKS_CLIENT_SECRET
    valueFrom: databricks_client_secret
  - name: DATABRICKS_HOST
    value: https://adb-3636121482767679.19.azuredatabricks.net
  - name: DATABRICKS_MODEL_ENDPOINT
    value: databricks-claude-3-7-sonnet
  - name: DATABRICKS_APP_URL
    value: https://u2m-agent-experiment-3636121482767679.19.azure.databricksapps.com

